/**
 * React hook wrapping TUS upload with progress speed/ETA tracking.
 *
 * Stateless utility hook -- returns a `startTusUpload` function that
 * creates and starts a TUS upload with an UploadSpeedTracker instance
 * for human-readable speed and ETA metrics.
 *
 * This hook does NOT import tus-js-client directly; it delegates to
 * the pure library module `@/lib/upload/tusUpload`.
 */

import { useCallback } from 'react';

import { createTusUpload, isTusSupported } from '@/lib/upload/tusUpload';
import { classifyUploadError } from '@/lib/upload/tusErrorClassifier';
import { UploadSpeedTracker } from '@/lib/upload/uploadMetrics';

export { isTusSupported };

interface TusUploadCallbacks {
  onProgress: (percentage: number, speed: string, eta: string) => void;
  onSuccess: (taskId: string) => void;
  onError: (userMessage: string, technicalDetail: string, isRetryable: boolean) => void;
  /** Fires when a retry is about to happen (before the delay). */
  onRetrying?: () => void;
}

/**
 * Stateless hook that provides a function to start a TUS upload
 * with integrated speed and ETA tracking, resume from previous
 * uploads, and classified error propagation.
 */
export function useTusUpload() {
  const startTusUpload = useCallback(
    (
      file: File,
      metadata: Record<string, string>,
      callbacks: TusUploadCallbacks,
    ): { abort: () => void } => {
      const speedTracker = new UploadSpeedTracker();

      // The taskId was pre-generated by the caller and included in metadata.
      // We pass it through on success -- no extraction from the TUS URL.
      const taskId = metadata.taskId;

      const upload = createTusUpload(file, metadata, {
        onProgress: (bytesSent: number, bytesTotal: number) => {
          const metrics = speedTracker.update(bytesSent, bytesTotal);
          callbacks.onProgress(
            metrics.percentage,
            metrics.speedFormatted,
            metrics.etaFormatted,
          );
        },
        onSuccess: () => {
          callbacks.onSuccess(taskId);
        },
        onError: (error: Error) => {
          const classified = classifyUploadError(error);
          callbacks.onError(
            classified.userMessage,
            classified.technicalDetail,
            classified.isRetryable,
          );
        },
        onBeforeRetry: callbacks.onRetrying,
      });

      // Async resume check + start (fire-and-forget, preserves sync return)
      (async () => {
        const previousUploads = await upload.findPreviousUploads();
        if (previousUploads.length > 0) {
          upload.resumeFromPreviousUpload(previousUploads[0]);
        }
        upload.start();
      })();

      return { abort: () => upload.abort(true) };
    },
    [],
  );

  return { startTusUpload };
}
